name = "pixyll"
description = "A simple, beautiful theme for Hugo."
author = "Dmitriy Slupytskyi"
license = "MIT"
source_repo = "https://github.com/azmelanar/hugo-theme-pixyll"
tags = ["blog", "personal", "search", "responsive", "minimal"]
min_version = 0.25
