languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseUrl = ""
canonifyurls = true
title = "Pixyll"
author = "admin"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  #search_engine = true
  #google_analytics_id = ""
  #twitter_username = ""
  #disqus_shortname = ""
