archetypeDir           = "archetypes"
author                 = "admin"
baseUrl                = "/"
buildDrafts            = false
relativeURLs           = true
canonifyUrls           = true
contentDir             = "content"
languageCode           = "en-us"
layoutDir              = "layouts"
publishDir             = "public"
theme                  = "hugo-theme-pixyll"
themesDir              = "../.."
title                  = "Pixyll"
enableEmoji            = true
DefaultContentLanguage = "en"

[Languages]
[Languages.en]
weight = 1

[Languages.ru]
weight = 2

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  search_engine = true
  #google_analytics_id = ""
  twitter_username = "username"
  #disqus_shortname = ""
  paginate = 5
